version: '3.8'

services:

  postgres:
    image: postgres:alpine
    container_name: db_client_test
    restart: always
    env_file:
      - config/.env
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: backend_client_test
    env_file:
      - config/.env
    volumes:
      - ./:/app
      - static:/app/static
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn delivery_client.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - postgres

  nginx:
    image: nginx:1.21.3-alpine
    restart: on-failure
    container_name: nginx_client_test
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
    links:
      - web
    depends_on:
      - web

volumes:
  pgdata:
  static:
