# Файл для примера СОЗДАНИЯ и заполнения файла .secrets.toml, секрентых
# настроек back-end сервера
[default]

[local]
SECRET_KEY = 'ключ проекта'
DATABASES__default__USER = 'логин к БД'
DATABASES__default__PASSWORD = 'пароль к БД'
DATABASES__default__NAME = 'название файла БД'
DATABASES__default__HOST = 'название хоста БД'
DATABASES__default__PORT = 'номер порта БД'

[development]
SECRET_KEY = ''
DATABASES__default__USER = ''
DATABASES__default__PASSWORD = ''
DATABASES__default__NAME = ''
DATABASES__default__HOST = ''
DATABASES__default__PORT = ''

[production]
SECRET_KEY = ''
DATABASES__default__USER = ''
DATABASES__default__PASSWORD = ''
DATABASES__default__NAME = ''
DATABASES__default__HOST = ''
DATABASES__default__PORT = ''
