#  Файл настроек для управления back-end сервером
[default] # -------------------------------------------------
SECRET_KEY = ''
DATABASES__default__ENGINE = 'django.db.backends.postgresql_psycopg2'
DATABASES__default__PORT = ''
DATABASES__default__HOST = ''
DATABASES__default__NAME = ''
DATABASES__default__USER = ''
DATABASES__default__PASSWORD = ''
DATABASES__default__ATOMIC_REQUESTS = false
DATABASES__default__AUTOCOMMIT = true
DATABASES__default__CONN_MAX_AGE = 0
REDIS_HOST=""
REDIS_PORT=''
REDIS_PASSWORD=""
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
ALLOWED_HOSTS = ['158.160.16.18', '127.0.0.1', 'localhost']
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
USE_I18N = true
USE_L10N = true
USE_TZ = true

REST_FRAMEWORK__PAGE_SIZE = 20
REST_FRAMEWORK__DEFAULT_THROTTLE_RATES = {anon = '5/min', user = '1/min'}
LOG_LEVEL = ''
ENV_NAME = 'default'

[local] # -------------------------------------------------
DEBUG = true
TIME_ZONE = 'Europe/Moscow'
LOG_LEVEL = 'DEBUG'
LOGURU_SERIALIZE = false
ENV_NAME = 'local'


[development] # -------------------------------------------------
DEBUG = false
ALLOWED_HOSTS = [
    '45.89.190.16',
    'delivery.dev.sarawan.ru'
]
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://80.90.188.195:3000/',
]
LOG_LEVEL = 'INFO'
LOGURU_SERIALIZE = false # true for write to db
MEDIA_ROOT = '/usr/local/bin/src/app/static/'
STATIC_ROOT = '/static/'
ENV_NAME = 'development'


[testing] # -------------------------------------------------
DEBUG = true
ALLOWED_HOSTS = [
    '45.89.190.16',
    'delivery.dev.sarawan.ru'
]
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://80.90.188.195:3000/',
]
LOG_LEVEL = 'DEBUG'
LOGURU_SERIALIZE = false
MEDIA_ROOT = ''
STATIC_ROOT = ''
ENV_NAME = 'testing'


[production] # -------------------------------------------------
DEBUG = false
ALLOWED_HOSTS = [
    '45.89.190.16',
    'delivery.dev.sarawan.ru'
]
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://80.90.188.195:3000/',
]
LOG_LEVEL = 'INFO'
LOGURU_SERIALIZE = false # true for write to db
MEDIA_ROOT = '/usr/local/bin/src/app/static/'
STATIC_ROOT = '/static/'
ENV_NAME = 'production'
